--PROBLEM 1  
-------------------------
--BASIC SELECT STATEMENTS 
------------------------- 
--PROBLEM STATEMENT 
-------------------------
--OUTPUT THE TOP 1 % OF THE PERSON.PERSON TABLE FROM THE ADVENTUREWORKS2022 DATABASE
--DISPLAY THE FIRST NAME, MIDDLE NAME AND LAST NAME COLUMNS
--AND ORDER ALPHABETICALLY BY LAST NAME AND THEN FIRST NAME 

SELECT TOP 1 PERCENT
	FirstName AS 'First Name', 
	MiddleName AS 'Middle Name', 
	LastName AS 'Last Name'
FROM Person.Person
ORDER BY 3 ASC, 1 ASC 